### ISSUE TITLE
Windows Packages?

### ISSUE THREAD

**Issue by Mason-P** [conda-forge/cvxopt-feedstock#13]
Hi, I am trying to install `cvxopt `using anaconda, but I am getting the following error:

`PackageNotFoundError: Package missing in current win-64 channels:
  - cvxopt`

I also tried  `conda install -c conda-forge cvxopt` and `pip install cvxopt` , still getting some error. Could you please help me with this issue. 

Thanks,

**Comment by jakirkham** [comment]
That's expected. As noted in the README of the feedstock, we don't currently build `cvxopt` for Windows. Sorry. 🙁

While it's certainly reasonable to request Windows packages, it's simply not easy to achieve given that most of the dependencies also don't support Windows at this time. Plus getting them to build on Windows is not trivial. So this is not likely to get completed any time soon without significant community engagement.

In the interim, I'd suggest using a Linux Docker container or possibly the Windows Subsystem for Linux (on Windows 10).

**Comment by Mason-P** [comment]
Thanks for your response @jakirkham. You mean there is no way to install it for Windows, even if I move to python 2.7? 

Thanks,

**Comment by jakirkham** [comment]
That's correct.

**Comment by jakirkham** [comment]
FWIW the situation has gotten better as `glpk` and `gsl` do have Windows builds. However we would still need to address `fftw` and `suitesparse`. The former has seen a bit of progress towards Windows support. However `suitesparse` is a different story.

**Comment by Mason-P** [comment]
Thanks, so still it is not gonna happen in a few days, right? 
BTW, I am not that experienced in Linux. So if I want to use Linux Docker or Windows subsystem for Linux as you suggested, do I need to install Anaconda again in the subsystem? or I can use it to install and use cvxopt?

**Comment by jakirkham** [comment]
> Thanks, so still it is not gonna happen in a few days, right?

Correct. Was more noting that this use to be totally impossible, but it is looking better in the long run.

> ...if I want to use Linux Docker or Windows subsystem for Linux as you suggested, do I need to install Anaconda again in the subsystem?

So these are totally different things IIUC.

With the Docker container, I'd recommend getting something that has been prebuilt with Miniconda or Anaconda installed. The [`condaforge/linux-anvil`]( https://hub.docker.com/r/condaforge/linux-anvil/ ) has Miniconda on it. Also the [Continuum Docker images]( https://github.com/ContinuumIO/docker-images ) would work as long as the `conda-forge` channel is given higher priority than `defaults`. As another option [Jupyter's docker-stacks]( https://github.com/jupyter/docker-stacks ), have preloaded Docker images with the Jupyter notebook and everything needed to make function plus relevant additions. Any of these would be a good starting place and it should be relatively easy to install `cvxopt` within this containers. Could also build your own container that extends from anyone of these and installs `cvxopt` as part of the container build. That way it is just ready to go.

I'm a little less clear on how the Windows subsystem for Linux works as I have not used this personally, but have heard good things from others who have tried it. My guess would be that you would need to install Miniconda or Anaconda in that environment. That said, it shouldn't be too difficult to do. Though this could be simply my lack of understanding/overly cautious response, it looks like they might [work together]( https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/ ).

**Comment by Mason-P** [comment]
HI @jakirkham! 

I am trying to install `cvxopt` on a linux server, but still, I am getting the following error:

```
conda install cvxopt
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa78a554da0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
```
Could you please help me with this error? Thank!

**Comment by jakirkham** [comment]
Are you able to ping google (i.e. `ping www.google.com`)?

**Comment by Mason-P** [comment]
This is what I get.
ping www.google.com
PING www.google.com (172.217.5.228) 56(84) bytes of data.
