### ISSUE TITLE
Possibly add DSDP5 support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cvxopt-feedstock#2]
Not sure that I want to do this, but I do want to make a note about the possibility.

cvxopt supports DSDP5 as an optional dependency, but is currently not being built with it. Might be worth considering packaging DSDP5 and adding it as a dependency.

However, it is a bit tricky as the most recent release of DSDP5 is over 10yrs old (2005). So, this may not be an easy dependency to package. Looking at the tarball suggested that there are going to have to be some special tweaks to get this to work right.

**Comment by martinandersen** [comment]
I created a DSDP recipe [here](https://github.com/martinandersen/dsdp-feedstock) with the intention of creating a conda-forge feedstock that CVXOPT can be linked against. It works on both macOS and Linux when built locally. @jakirkham would you be willing to help create (and maintain?) a feedstock? 

On a related note, I'm not sure what kind of license this is:
http://www.mcs.anl.gov/hs/software/DSDP/Copyright.txt

**Comment by jakirkham** [comment]
I may be somewhat limited in terms of time, but can try to help answer questions and do the initial review if you’d like to open a `staged-recipes` PR. Just ping me in that PR once it is live.

**Comment by jakirkham** [comment]
Being addressed in PR ( https://github.com/conda-forge/cvxopt-feedstock/pull/19 ).
