### ISSUE TITLE
cvxopt on windows effectively uninstallable

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cvxopt-feedstock#41]
Since #38, there exists a windows build of this feedstock, however, it remains essentially uninstallable (as I'll explain). For #38, I didn't touch the existing host-requirement
```
    - suitesparse         # [not win]
    - suitesparse 5.1.*   # [win]
```

and it seems this is creating an incompatibility with all newer versions of openblas (it's possible that I'm overlooking another reason, but this is the only thing that jumps out at me from the recipe and the recipes of the dependencies).

Hence, the conda solver will usually suggest the build from the main channel (note: conda-forge has a higher priority in my channels):
```
>conda install cvxopt
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Users\xxx\.conda\envs\cvxopt_test

  added / updated specs:
    - cvxopt


The following NEW packages will be INSTALLED:

  cvxopt             pkgs/main/win-64::cvxopt-1.2.0-py36hdc3235a_0
  glpk               conda-forge/win-64::glpk-4.65-h2fa13f4_1002
  gsl                conda-forge/win-64::gsl-2.4-h631dd0c_1006


Proceed ([y]/n)?
```

And if forced to choose the conda-forge build, it would lead to large-scale downgrades across packages (esp. from the scientific stack) as openblas is incompatible.

Xref conda-forge/suitesparse-feedstock#51.

**Comment by h-vetinari** [comment]
While following up on conda-forge/suitesparse-feedstock#51 and investigating what would be necessary for a windows build, I wanted to check the [anaconda recipe](https://github.com/conda-forge/cvxopt-feedstock/blob/master/recipe/meta.yaml) and found to my great surprise that @nehaljwani is building suitesparse directly within the cvxopt-feedstock.

I'm assuming that it is not a problem (much less a licence one with the same licence) if I try to take this over in a PR here.

**Comment by nehaljwani** [comment]
I don't remember the license situation. I was just updating the feedstock from the conda package at the time. @msarahan had worked on it. That being said, even if multiple licenses are involved, one can specify multiple licenses in the feedstock too.
