### ISSUE TITLE
Build for osx-arm64

### ISSUE THREAD

**Issue by kharteveld** [conda-forge/cvxopt-feedstock#48]
Hi,
Would it be possible to create a CVXOPT build for the new MacBooks (with the osx-arm64 chips)? It is the only package for my project that doesn't yet run on my new laptop, and an attempt to build it myself failed miserably.
Thanks!

**Comment by jakirkham** [comment]
Please send a PR to [add it to this list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt ).

**Comment by kharteveld** [comment]
I added it to the list. Thanks!

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1042
